import type { Metadata } from "next";
import { Inter, Noto_Sans } from "next/font/google";
import "./style/globals.css";
import { ConfigProvider } from "antd";
import { NextIntlClientProvider } from "next-intl";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { getLocale, getMessages } from "next-intl/server";

const noto_sans = Noto_Sans({
  subsets: ["latin"],
  display: 'swap',
  weight: ["400", "500", "600", '700', "800"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={noto_sans.className}>
        <ConfigProvider theme={{ token: { fontFamily: noto_sans.style.fontFamily }}}>
          <AntdRegistry>
            <NextIntlClientProvider messages={messages}>
              {children}
            </NextIntlClientProvider>
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
